language: "node_js"
node_js:
  - "4.2"
  - "5.1"
  - "6.9"
  - "7.2"
  - "8.0"
  - "9.0"
  - "10.0"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - export CXX="g++-4.8"
sudo: false
